#!/bin/sh

set -e

# Fix permissions
chown root:freerad /etc/yubico/rlm/*
chmod 640 /etc/yubico/rlm/*
chmod 660 /etc/yubico/rlm/ykmapping

# Enable rlm_yubikey site
if [ ! -L /etc/freeradius/sites-enabled/yubikey-default ]; then
    ln -s /usr/share/rlm_yubikey/yubikey-default /etc/freeradius/sites-enabled/yubikey-default
fi

# Disable default site
if [ -L /etc/freeradius/sites-enabled/default ]; then
    rm -f /etc/freeradius/sites-enabled/default
fi

#DEBHELPER#

if [ -x /usr/sbin/invoke-rc.d ]; then
    invoke-rc.d freeradius reload 3>/dev/null || true
else
    /etc/init.d/freeradius reload 3>/dev/null || true
fi

exit 0
